#pragma once

struct CNodeCall;
struct CNodeClass;
struct CNodeCompound;
struct CNodeConstructor;
struct CNodeDeclaration;
struct CNodeEnum;
struct CNodeExpression;
struct CNodeField;
struct CNodeFieldExpression;
struct CNodeFunction;
struct CNodeIdentifier;
struct CNodeKeyword;
struct CNodeList;
struct CNodeNamespace;
struct CNodePreproc;
struct CNodePunct;
struct CNodeQualifiedIdentifier;
struct CNodeStatement;
struct CNodeStruct;
struct CNodeTranslationUnit;
struct CNodeType;
struct CNodeTypedef;
struct Cursor;
